# Project - $k$-Nearest-Neighbors Classifier
- Create a $k$-Nearest-Neighbors Classifier supporting 3 dimensions
- Investigate whether it performs better

### Step 1: Import libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2: Read data
- Use pandas [read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) method to read **files/weather.csv**
- HINT: Use **parse_dates=True** and **index_col=0**

In [2]:
data = pd.read_csv('files/weather.csv', parse_dates=True, index_col =0)

### Step 3: Investigate data types
- Use [dtypes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dtypes.html)
- The goal is to identify all columns with datatype **float64** for next step

In [4]:
data.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [5]:
data.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
Date                                                                        
2008-02-01     19.5     22.4      15.6          6.2       0.0         NaN   
2008-02-02     19.5     25.6       6.0          3.4       2.7         NaN   
2008-02-03     21.6     24.5       6.6          2.4       0.1         NaN   
2008-02-04     20.2     22.8      18.8          2.2       0.0         NaN   
2008-02-05     19.7     25.7      77.4          NaN       0.0         NaN   

            WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  \
Date                                                           ...   
2008-02-01            NaN          S        SSW          17.0  ...   
2008-02-02            NaN          W          E           9.0  ...   
2008-02-03            NaN        ESE        ESE          17.0  ...   
2008-02-04            NaN        NNE          E          22.0  ...   
2008-02-05            NaN        NNE          W          11.0  ...   

            Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
Date                                                                    
2008-02-01         84.0       1017.6       1017.4       8.0       8.0   
2008-02-02         73.0       1017.9       1016.4       7.0       7.0   
2008-02-03         86.0       1016.7       1015.6       7.0       8.0   
2008-02-04         90.0       1014.2       1011.8       8.0       8.0   
2008-02-05         74.0       1008.3       1004.8       8.0       8.0   

            Temp9am  Temp3pm  RainToday  RISK_MM RainTomorrow  
Date                                                           
2008-02-01     20.7     20.9        Yes      6.0          Yes  
2008-02-02     22.4     24.8        Yes      6.6          Yes  
2008-02-03     23.5     23.0        Yes     18.8          Yes  
2008-02-04     21.4     20.9        Yes     77.4          Yes  
2008-02-05     22.5     25.5        Yes      1.6          Yes  

[5 rows x 22 columns]

In [6]:
data.index

DatetimeIndex(['2008-02-01', '2008-02-02', '2008-02-03', '2008-02-04',
               '2008-02-05', '2008-02-06', '2008-02-07', '2008-02-08',
               '2008-02-09', '2008-02-10',
               ...
               '2017-06-16', '2017-06-17', '2017-06-18', '2017-06-19',
               '2017-06-20', '2017-06-21', '2017-06-22', '2017-06-23',
               '2017-06-24', '2017-06-25'],
              dtype='datetime64[ns]', name='Date', length=3337, freq=None)

In [7]:
len(data)

3337

### Step 4: Choose 3 columns to create datasets
- Use **Humidity3pm** and **Pressure3pm** together with another column to predict **RainTomorrow**
- Make a list of three column names **'Humidity3pm', 'Pressure3pm', INSERT YOUR CHOICE** (should be one with dtype *float64*, e.g., **Cloud3pm**), and **'RainTomorrow'**
- Create the dataset consisting of these 4 columns

In [8]:
dataset= data[['Humidity3pm', 'Pressure3pm','Evaporation', 'RainTomorrow']]

### Step 5: Deal with remaining missing data
- A simple choice is to simply remove rows with missing data
- Use [dropna()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.dropna.html)

In [9]:
dataclean = dataset.dropna()

In [10]:
len(dataclean), len(dataset)

(3258, 3337)

### Step 6: Create training and test datasets
- Define dataset **X** to be the data consisting of the three columns.
- Define dataset **y** to be datset cosisting of **'RainTomorrow'**.
    - HINT: Use list comprehension to transform **'No'** and **'Yes'** to 0 and 1, repectively (like in the Lesson)
- Divide into **X_train, X_test, y_train, y_test** with **train_test_split**
    - HINT: See how it is done in Lesson
    - You can use **random_state=42** (or any other number) if you want to reproduce results.

In [22]:
X = dataclean[['Humidity3pm', 'Pressure3pm', 'Evaporation']]
y = dataclean['RainTomorrow']
y = np.array([0 if value == 'No' else 1 for value in y])

In [23]:
len(y), len(X)

(3258, 3258)

### Step 7: Train and test the model
- Create classifier with **KNeighborsClassifier**
    - You can play around with n_neighbors (default =5)
- Fit the model with training data **(X_train, y_train**)
- Predict data from **X_test** (use predict) and assign to **y_pred**.
- Evalute score by using **metrics.accuracy_score(y_test, y_pred)**.

In [24]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [45]:
print(X_train.shape)
print(X_test.shape)

(1267, 5)
(423, 5)


In [42]:
X_train.head()

Evaporation  Sunshine  WindSpeed3pm  Humidity3pm  Pressure3pm
Date                                                                     
2012-07-22          3.6       6.8          20.0         62.0       1027.6
2013-12-16          7.0       6.4          24.0         60.0       1019.2
2016-06-19          0.8       0.0          20.0         89.0       1010.4
2014-03-19          6.6      10.1          26.0         57.0       1023.6
2015-04-19          6.6       6.6          35.0         69.0       1019.6

In [59]:
print((len(X_train)/(len(X_train)+len(X_test))*100))

74.97041420118343


In [60]:
dataset.groupby('RainTomorrow').count()/len(dataset)

Humidity3pm  Pressure3pm  Evaporation
RainTomorrow                                       
No               0.737788     0.736290     0.734492
Yes              0.258316     0.258016     0.250225

In [62]:
dataset.groupby('RainTomorrow')['Humidity3pm'].count()/len(dataset)

RainTomorrow
No     0.737788
Yes    0.258316
Name: Humidity3pm, dtype: float64

In [26]:
neigh = KNeighborsClassifier()
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
accuracy_score(y_test, y_pred)

0.8012269938650307

In [28]:
data.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm     float64
Humidity9am      float64
Humidity3pm      float64
Pressure9am      float64
Pressure3pm      float64
Cloud9am         float64
Cloud3pm         float64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [30]:
dataset1 = data[['Rainfall', 'Evaporation', 'Sunshine','WindSpeed3pm','Humidity3pm','Pressure3pm', 'RainTomorrow' ]]

In [31]:
dataclean1 = data.dropna()

### Step 8 (Optional): Try with different columns
- You can redo with diffrent choise of columns (starting from step 4)

In [32]:
len(dataclean1), len(data)

(1690, 3337)

In [33]:
X = dataclean1[['Rainfall', 'Evaporation', 'Sunshine','WindSpeed3pm','Humidity3pm','Pressure3pm']]
y = dataclean1['RainTomorrow']
y = np.array([0 if value == 'No' else 1 for value in y])

In [70]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

## Funcionamiento de train_test_split
https://interactivechaos.com/es/python/function/sklearnmodelselectiontraintestsplit

In [37]:
neigh = KNeighborsClassifier()
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
accuracy_score(y_test, y_pred)

0.8132387706855791

In [36]:
X = dataclean1[['Evaporation', 'Sunshine','WindSpeed3pm','Humidity3pm','Pressure3pm']]
y = dataclean1['RainTomorrow']
y = np.array([0 if value == 'No' else 1 for value in y])

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

train_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the
    proportion of the dataset to include in the train split. If
    int, represents the absolute number of train samples. If None,
    the value is automatically set to the complement of the test size.

random_state : int, RandomState instance or None, default=None
    Controls the shuffling applied to the data before applying the split.
    Pass an int for reproducible output across multiple function calls.
    See :term:`Glossary <random_state>`.

shuffle : bool, default=True
    Whether or not to shuffle the data before splitting. If shuffle=False
    then stratify must be None.

stratify : array-like, default=None
    If not None, data is split in a stratified fashion, using this as
    the class labels.
    Read more in the :ref:`User Guide <stratification>`.

Returns
-------
splitting : list, length=2 * len(arrays)
    List containing train-test split of inputs.

    .. versionadded:: 0.16
        If the input is sparse, the output will be a
        ``scipy.sparse.csr_matrix``. Else, output type is the same as the
        input type.

Examples
--------
>>> import numpy as np
>>> from sklearn.model_selection import train_test_split
>>> X, y = np.arange(10).reshape((5, 2)), range(5)
>>> X
array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])
>>> list(y)
[0, 1, 2, 3, 4]

>>> X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)
...
>>> X_train
array([[4, 5],
       [0, 1],
       [6, 7]])
>>> y_train
[2, 0, 3]
>>> X_test
array([[2, 3],
       [8, 9]])
>>> y_test
[1, 4]

>>> train_test_split(y, shuffle=False)
[[0, 1, 2], [3, 4]]
File:      c:\users\owner\anaconda3\lib\site-packages\sklearn\model_selection\_split.py
Type:      function

In [39]:
neigh = KNeighborsClassifier()
neigh.fit(X_train, y_train)
y_pred = neigh.predict(X_test)
accuracy_score(y_test, y_pred)

0.8274231678486997